USE EC1_CC1M;

#Inserções na Tabela FORNECEDORES
INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO) 
VALUES (1, 'Fornecedor A', 'Rua 1', 100, 'Centro', 'São Paulo', 'SP', 'Brasil', '01000-000', '1111-1111', 'João');
INSERT INTO FORNECEDORES VALUES (2, 'Fornecedor B', 'Rua 2', 200, 'Jardim', 'Curitiba', 'PR', 'Brasil', '81000-000', '2222-2222', 'Maria');
INSERT INTO FORNECEDORES VALUES (3, 'Fornecedor C', 'Rua 3', 300, 'Industrial', 'Manaus', 'AM', 'Brasil', '69000-000', '3333-3333', 'Carlos');
INSERT INTO FORNECEDORES VALUES (4, 'Fornecedor D', 'Rua 4', 400, 'Sul', 'Porto Alegre', 'RS', 'Brasil', '90000-000', '4444-4444', 'Ana');
INSERT INTO FORNECEDORES VALUES (5, 'Fornecedor E', 'Rua 5', 500, 'Leste', 'Fortaleza', 'CE', 'Brasil', '60000-000', '5555-5555', 'Paulo');

#Atualizações na Tabela FORNECEDORES
UPDATE FORNECEDORES SET FORNEC_TELEFONE = '6666-6666' WHERE FORNEC_COD = 1;
UPDATE FORNECEDORES SET FORNEC_CIDADE = 'Brasília' WHERE FORNEC_NOME = 'Fornecedor D';

#Exclusão na Tabela FORNECEDORES
DELETE FROM FORNECEDORES WHERE FORNEC_COD = 5;


#Inserções na Tabela FILIAIS
INSERT INTO FILIAIS (FILIAL_COD, FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE, FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE) 
VALUES (1, 'Filial Norte', 'Rua Principal', 1000, 'Centro', 'Belém', 'PA', 'Brasil', '66000-000', 'Grande');
INSERT INTO FILIAIS VALUES (2, 'Filial Sul', 'Avenida Sul', 1200, 'Zona Sul', 'Curitiba', 'PR', 'Brasil', '80000-000', 'Média');
INSERT INTO FILIAIS VALUES (3, 'Filial Oeste', 'Rua Oeste', 1300, 'Vila Oeste', 'São Paulo', 'SP', 'Brasil', '05000-000', 'Grande');
INSERT INTO FILIAIS VALUES (4, 'Filial Leste', 'Rua Leste', 1400, 'Zona Leste', 'Rio de Janeiro', 'RJ', 'Brasil', '21000-000', 'Média');
INSERT INTO FILIAIS VALUES (5, 'Filial Central', 'Avenida Central', 1500, 'Centro', 'Brasília', 'DF', 'Brasil', '70000-000', 'Pequena');

//Atualizações na Tabela FILIAIS
UPDATE FILIAIS SET FILIAL_CAPACIDADE = 'Muito Grande' WHERE FILIAL_COD = 1;
UPDATE FILIAIS SET FILIAL_ESTADO = 'MG' WHERE FILIAL_COD = 4;

#Exclusão na Tabela FILIAIS
DELETE FROM FILIAIS WHERE FILIAL_COD = 3;


#Inserções na Tabela PRODUTOS
INSERT INTO PRODUTOS (PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN) 
VALUES (1, 'Notebook', 'Notebook 14"', 'Intel i5, 8GB RAM', 50, 3500.00, 'Unidade', 5);
INSERT INTO PRODUTOS VALUES (2, 'Monitor', 'Monitor 24"', 'Full HD', 70, 900.00, 'Unidade', 10);
INSERT INTO PRODUTOS VALUES (3, 'Teclado', 'Teclado Mecânico', 'Switch Blue', 100, 250.00, 'Unidade', 20);
INSERT INTO PRODUTOS VALUES (4, 'Mouse', 'Mouse Sem Fio', 'Óptico', 150, 100.00, 'Unidade', 15);
INSERT INTO PRODUTOS VALUES (5, 'Impressora', 'Impressora Multifuncional', 'Laser', 30, 1200.00, 'Unidade', 8);

#Atualizações na Tabela PRODUTOS
UPDATE PRODUTOS SET PROD_PRECOUNIT = 4000.00 WHERE PROD_COD = 1;
UPDATE PRODUTOS SET PROD_QUANT = PROD_QUANT + 20 WHERE PROD_COD = 2;

#Exclusão na Tabela PRODUTOS
DELETE FROM PRODUTOS WHERE PROD_COD = 5;


#Inserções na Tabela PEDIDOS
INSERT INTO PEDIDOS (PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FILIAL) 
VALUES (1, '2024-04-01', '10:00:00', '2024-04-07', 'PENDENTE', 1);
INSERT INTO PEDIDOS VALUES (2, '2024-04-02', '11:00:00', '2024-04-08', 'EM ESPERA', 2);
INSERT INTO PEDIDOS VALUES (3, '2024-04-03', '14:30:00', '2024-04-09', 'CONCLUÍDO', 3);
INSERT INTO PEDIDOS VALUES (4, '2024-04-04', '09:15:00', '2024-04-10', 'PENDENTE', 4);
INSERT INTO PEDIDOS VALUES (5, '2024-04-05', '16:45:00', '2024-04-11', 'EM ESPERA', 1);

#Atualizações na Tabela PEDIDOS
UPDATE PEDIDOS SET PED_STATUS = 'CONCLUÍDO' WHERE PED_CODIGO = 1;
UPDATE PEDIDOS SET PED_PREVISAO = '2024-04-12' WHERE PED_CODIGO = 5;

#Exclusão na Tabela PEDIDOS
DELETE FROM PEDIDOS WHERE PED_CODIGO = 5;


#Inserções na Tabela RECEBIMENTOS
INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS) 
VALUES ('2024-04-07', '12:00:00', 10, 'Ótima', 1);
INSERT INTO RECEBIMENTOS VALUES ('2024-04-08', '14:30:00', 20, 'Boa', 2);
INSERT INTO RECEBIMENTOS VALUES ('2024-04-09', '10:15:00', 15, 'Regular', 3);
INSERT INTO RECEBIMENTOS VALUES ('2024-04-10', '09:45:00', 12, 'Ótima', 4);
INSERT INTO RECEBIMENTOS VALUES ('2024-04-11', '11:30:00', 8, 'Ruim', 1);

#Atualizações na Tabela RECEBIMENTOS
UPDATE RECEBIMENTOS SET RECEB_CONDICAO = 'Excelente' WHERE RECEB_PEDIDOS = 1;
UPDATE RECEBIMENTOS SET RECEB_QUANT_PROD = RECEB_QUANT_PROD + 5 WHERE RECEB_PEDIDOS = 2;

#Exclusão na Tabela RECEBIMENTOS
DELETE FROM RECEBIMENTOS WHERE RECEB_PEDIDOS = 3;

