CREATE SCHEMA EC4_CC1M;

USE EC4_CC1M;

#CRIANDO A TABELA ALUNOS
CREATE TABLE IF NOT EXISTS ALUNOS(
ALUNO_CPF VARCHAR(14) PRIMARY KEY,
ALUNO_NOME VARCHAR(50) NOT NULL,
ALUNO_DATANASC DATE NOT NULL,
ALUNO_RUA VARCHAR(45) NOT NULL,
ALUNO_NUMRUA INT,
ALUNO_BAIRRO VARCHAR(45) NOT NULL,
ALUNO_CIDADE VARCHAR(45) NOT NULL,
ALUNO_ESTADO VARCHAR(45) NOT NULL,
ALUNO_PAIS VARCHAR(30) NOT NULL,
ALUNO_CODPOSTAL VARCHAR(10) NOT NULL,
ALUNO_TELEFONE VARCHAR(15) NOT NULL,
ALUNO_EMAIL VARCHAR(50) NOT NULL
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA ALUNOS
ALTER TABLE ALUNOS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE ALUNOS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE ALUNOS CHANGE DESCRICAO ALUNO_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE ALUNOS DROP ALUNO_DESCRICAO;

#CRIANDO A TABELA INSTRUTORES
CREATE TABLE IF NOT EXISTS INSTRUTORES(
INSTRU_COD INT PRIMARY KEY,
INSTRU_NOME VARCHAR(50) NOT NULL,
INSTRU_TELEFONE VARCHAR(15) NOT NULL,
INSTRU_EMAIL VARCHAR(50) NOT NULL
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA INSTRUTORES
ALTER TABLE INSTRUTORES ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE INSTRUTORES MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE INSTRUTORES CHANGE DESCRICAO INSTRU_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE INSTRUTORES DROP INSTRU_DESCRICAO;

#CRIANDO A TABELA MODALIDADES
CREATE TABLE IF NOT EXISTS MODALIDADES(
MODAL_COD INT PRIMARY KEY,
MODAL_NOME VARCHAR(50) NOT NULL
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA MODALIDADES
ALTER TABLE MODALIDADES ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE MODALIDADES MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE MODALIDADES CHANGE DESCRICAO MODAL_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE MODALIDADES DROP MODAL_DESCRICAO;

#CRIANDO A TABELA PAGAMENTOS
CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_COD INT PRIMARY KEY,
PAG_STATUS ENUM('PAGO', 'PENDENTE') NOT NULL,
PAG_VALOR DECIMAL(5,2) NOT NULL,
PAG_DATA DATE NOT NULL,
PAG_ALUNO VARCHAR(14) NOT NULL,
CONSTRAINT FK_ALUNOS FOREIGN KEY (PAG_ALUNO) REFERENCES ALUNOS(ALUNO_CPF)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA PAGAMENTOS
ALTER TABLE PAGAMENTOS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE PAGAMENTOS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PAGAMENTOS CHANGE DESCRICAO PAG_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PAGAMENTOS DROP PAG_DESCRICAO;

#CRIANDO A TABELA PLANOS_TREINAMENTO
CREATE TABLE IF NOT EXISTS PLANOS_TREINAMENTO(
PT_COD INT PRIMARY KEY,
PT_STATUS VARCHAR(100) NOT NULL,
PT_INSTRU INT NOT NULL,
PT_ALUNO VARCHAR(14) NOT NULL,
CONSTRAINT FK_INSTRUTORES FOREIGN KEY (PT_INSTRU) REFERENCES INSTRUTORES(INSTRU_COD),
CONSTRAINT FK_ALUNOS_PLANO FOREIGN KEY (PT_ALUNO) REFERENCES ALUNOS(ALUNO_CPF)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA PLANOS_TREINAMENTO
ALTER TABLE PLANOS_TREINAMENTO ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE PLANOS_TREINAMENTO MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PLANOS_TREINAMENTO CHANGE DESCRICAO PT_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PLANOS_TREINAMENTO DROP PT_DESCRICAO;

#CRIANDO A TABELA AULAS
CREATE TABLE IF NOT EXISTS AULAS(
AULA_COD INT PRIMARY KEY,
AULA_DATA DATE NOT NULL,
AULA_HORA TIME NOT NULL,
AULA_CAPACIDADE INT NOT NULL,
AULA_INSTRUTOR INT NOT NULL,
AULA_MODALIDADE INT NOT NULL,
CONSTRAINT FK_INSTRUTOR_AULA FOREIGN KEY (AULA_INSTRUTOR) REFERENCES INSTRUTORES(INSTRU_COD),
CONSTRAINT FK_MODALIDADE FOREIGN KEY (AULA_MODALIDADE) REFERENCES MODALIDADES(MODAL_COD)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA AULAS
ALTER TABLE AULAS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE AULAS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE AULAS CHANGE DESCRICAO AULA_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE AULAS DROP AULA_DESCRICAO;

#CRIANDO A TABELA AULAS_ALUNOS
CREATE TABLE IF NOT EXISTS AULAS_ALUNOS(
ALAN_ALUNO VARCHAR(14),
ALAN_AULA INT,
PRIMARY KEY(ALAN_ALUNO, ALAN_AULA),
CONSTRAINT FK_ALUNOS_OP FOREIGN KEY (ALAN_ALUNO) REFERENCES ALUNOS(ALUNO_CPF),
CONSTRAINT FK_AULAS FOREIGN KEY (ALAN_AULA) REFERENCES AULAS(AULA_COD)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA AULAS_ALUNOS
ALTER TABLE AULAS_ALUNOS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE AULAS_ALUNOS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE AULAS_ALUNOS CHANGE DESCRICAO ALAN_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE AULAS_ALUNOS DROP ALAN_DESCRICAO;

#CRIANDO A TABELA DRACULA
CREATE TABLE IF NOT EXISTS DRACULA(
DRAC_COD INT PRIMARY KEY
);

#ESTABELECENDO COMANDO DE DROP NA TABELA DRACULA
DROP TABLE DRACULA;
