CREATE SCHEMA EC5_CC1M;

USE EC5_CC1M;

#CRIANDO A TABELA CLIENTES
CREATE TABLE IF NOT EXISTS CLIENTES(
CLIEN_CPF VARCHAR(14) PRIMARY KEY,
CLIEN_NOME VARCHAR(50) NOT NULL,
CLIEN_DATANASC DATE NOT NULL,
CLIEN_STATUS VARCHAR(50) NOT NULL,
CLIEN_RUA VARCHAR(45) NOT NULL,
CLIEN_NUMRUA INT,
CLIEN_BAIRRO VARCHAR(45) NOT NULL,
CLIEN_CIDADE VARCHAR(45) NOT NULL,
CLIEN_ESTADO VARCHAR(45) NOT NULL,
CLIEN_PAIS VARCHAR(30) NOT NULL,
CLIEN_CODPOSTAL VARCHAR(10) NOT NULL,
CLIEN_TELEFONE VARCHAR(15) NOT NULL,
CLIEN_EMAIL VARCHAR(50) NOT NULL
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA CLIENTES
ALTER TABLE CLIENTES ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE CLIENTES MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE CLIENTES CHANGE DESCRICAO CLIEN_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE CLIENTES DROP CLIEN_DESCRICAO;

#CRIANDO A TABELA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_ESTOQUE INT NOT NULL,
PROD_PRECO DECIMAL(5,2) NOT NULL
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA PRODUTOS
ALTER TABLE PRODUTOS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE PRODUTOS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PRODUTOS CHANGE DESCRICAO PROD_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PRODUTOS DROP PROD_DESCRICAO;

#CRIANDO A TABELA FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORN_COD INT PRIMARY KEY,
FORN_NOME VARCHAR(50) NOT NULL,
FORN_TELEFONE VARCHAR(15) NOT NULL,
FORN_EMAIL VARCHAR(50) NOT NULL,
FORN_RUA VARCHAR(45) NOT NULL,
FORN_NUMRUA INT,
FORN_BAIRRO VARCHAR(45) NOT NULL,
FORN_CIDADE VARCHAR(45) NOT NULL,
FORN_ESTADO VARCHAR(45) NOT NULL,
FORN_PAIS VARCHAR(30) NOT NULL,
FORN_CODPOSTAL VARCHAR(10) NOT NULL
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA FORNECEDORES
ALTER TABLE FORNECEDORES ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE FORNECEDORES MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE FORNECEDORES CHANGE DESCRICAO FORN_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE FORNECEDORES DROP FORN_DESCRICAO;

#CRIANDO A TABELA VENDAS
CREATE TABLE IF NOT EXISTS VENDAS(
VENDA_COD INT PRIMARY KEY,
VENDA_VALOR DECIMAL(5,2) NOT NULL,
VENDA_FORMAPAG VARCHAR(20) NOT NULL,
VENDA_CLIENTE VARCHAR(14) NOT NULL,
CONSTRAINT FK_CLIENTES FOREIGN KEY (VENDA_CLIENTE) REFERENCES CLIENTES(CLIEN_CPF)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA VENDAS
ALTER TABLE VENDAS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE VENDAS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE VENDAS CHANGE DESCRICAO VENDA_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE VENDAS DROP VENDA_DESCRICAO;

#CRIANDO A TABELA PAGAMENTOS
CREATE TABLE IF NOT EXISTS PAGAMENTOS(
PAG_COD INT PRIMARY KEY NOT NULL,
PAG_DATA DATE NOT NULL,
PAG_VALOR DECIMAL(5,2) NOT NULL,
PAG_STATUS ENUM('PAGO', 'PENDENTE') NOT NULL,
PAG_VENDA INT NOT NULL,
CONSTRAINT FK_VENDAS FOREIGN KEY (PAG_VENDA) REFERENCES VENDAS(VENDA_COD)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA PAGAMENTOS
ALTER TABLE PAGAMENTOS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE PAGAMENTOS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PAGAMENTOS CHANGE DESCRICAO PAG_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PAGAMENTOS DROP PAG_DESCRICAO;

#CRIANDO A TABELA PRODUTOS_FORNECEDORES
CREATE TABLE IF NOT EXISTS PRODUTOS_FORNECEDORES(
FRPR_FORNECEDORES INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDORES,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDORES) REFERENCES FORNECEDORES(FORN_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA PRODUTOS_FORNECEDORES
ALTER TABLE PRODUTOS_FORNECEDORES ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE PRODUTOS_FORNECEDORES MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PRODUTOS_FORNECEDORES CHANGE DESCRICAO FRPR_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PRODUTOS_FORNECEDORES DROP FRPR_DESCRICAO;

#CRIANDO A TABELA PRODUTOS_VENDAS
CREATE TABLE IF NOT EXISTS PRODUTOS_VENDAS(
VNPR_VENDAS INT,
VNPR_PRODUTOS INT,
PRIMARY KEY(VNPR_VENDAS,VNPR_PRODUTOS),
VNPR_QUANTPROD INT NOT NULL,
CONSTRAINT VNPR_FK_VENDAS FOREIGN KEY(VNPR_VENDAS) REFERENCES VENDAS(VENDA_COD),
CONSTRAINT VNPR_FK_PRODUTOS FOREIGN KEY(VNPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA PRODUTOS_VENDAS
ALTER TABLE PRODUTOS_VENDAS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE PRODUTOS_VENDAS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PRODUTOS_VENDAS CHANGE DESCRICAO VNPR_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PRODUTOS_VENDAS DROP VNPR_DESCRICAO;

#CRIANDO A TABELA BELMONT
CREATE TABLE IF NOT EXISTS BELMONT(
BELMONT_COD INT PRIMARY KEY
);

#ESTABELECENDO O COMANDO DE DROP NA TABELA BELMONT
DROP TABLE BELMONT;
