CREATE SCHEMA EC2_CC1M;

USE EC2_CC1M;

#CRIANDO A TABELA PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF VARCHAR(14) PRIMARY KEY,
PASS_NOME VARCHAR(100) NOT NULL,
PASS_TELEFONE VARCHAR(30) NOT NULL,
PASS_EMAIL VARCHAR(100) NOT NULL,
PASS_RUA VARCHAR(100) NOT NULL,
PASS_NUMRUA INT,
PASS_BAIRRO VARCHAR(50) NOT NULL,
PASS_CIDADE VARCHAR(50) NOT NULL,
PASS_ESTADO VARCHAR(50) NOT NULL,
PASS_PAIS VARCHAR(50) NOT NULL,
PASS_CODPOSTAL VARCHAR(10) NOT NULL
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA PASSAGEIROS
ALTER TABLE PASSAGEIROS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE PASSAGEIROS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PASSAGEIROS CHANGE DESCRICAO PASS_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE PASSAGEIROS DROP PASS_DESCRICAO;

#CRIANDO A TABELA AEROPORTOS
CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_CODIGO INT PRIMARY KEY,
AEROP_NOME VARCHAR(100) NOT NULL,
AEROP_CIDADE VARCHAR(100) NOT NULL,
AEROP_PAIS VARCHAR(100) NOT NULL,
AEROP_LATITUDE DECIMAL(3,2) NOT NULL,
AEROP_LONGITUDE DECIMAL(3,2) NOT NULL
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA AEROPORTOS
ALTER TABLE AEROPORTOS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE AEROPORTOS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE AEROPORTOS CHANGE DESCRICAO AEROP_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE AEROPORTOS DROP AEROP_DESCRICAO;

#CRIANDO A TABELA FUNCIONARIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR(100) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_CPF VARCHAR(14) NOT NULL,
FUNC_FUNCAO VARCHAR(100) NOT NULL,
FUNC_RUA VARCHAR(100) NOT NULL,
FUNC_NUMRUA INT,
FUNC_BAIRRO VARCHAR(50) NOT NULL,
FUNC_CIDADE VARCHAR(50) NOT NULL,
FUNC_ESTADO VARCHAR(50) NOT NULL,
FUNC_PAIS VARCHAR(50) NOT NULL,
FUNC_CODPOSTAL VARCHAR(10) NOT NULL
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA FUNCIONARIOS
ALTER TABLE FUNCIONARIOS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE FUNCIONARIOS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE FUNCIONARIOS CHANGE DESCRICAO FUNC_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE FUNCIONARIOS DROP FUNC_DESCRICAO;

#CRIANDO A TABELA AERONAVES
CREATE TABLE IF NOT EXISTS AERONAVES(
AERON_PREFIXO VARCHAR(100) PRIMARY KEY,
AERON_MODELO VARCHAR(100) NOT NULL,
AERON_ANOFABR INT NOT NULL,
AERON_AUTONOMIA VARCHAR(100) NOT NULL,
AERON_CAPACIDADE INT NOT NULL,
AERON_FABRICANTE VARCHAR(100) NOT NULL
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA AERONAVES
ALTER TABLE AERONAVES ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE AERONAVES MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE AERONAVES CHANGE DESCRICAO AERON_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE AERONAVES DROP AERON_DESCRICAO;

#CRIANDO A TABELA VOOS
CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AEROP_ORIGEM INT NOT NULL,
VOO_AEROP_DESTINO INT NOT NULL,
VOO_AERONAVE VARCHAR(100) NOT NULL,
CONSTRAINT FK_AEROPORTOS_ORIIGEM FOREIGN KEY (VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_CODIGO),
CONSTRAINT FK_AEROPORTOS_DESTINO FOREIGN KEY (VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_CODIGO),
CONSTRAINT FK_AERONAVES FOREIGN KEY (VOO_AERONAVE) REFERENCES AERONAVES(AERON_PREFIXO)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA VOOS
ALTER TABLE VOOS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE VOOS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE VOOS CHANGE DESCRICAO VOO_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE VOOS DROP VOO_DESCRICAO;

#CRIANDO A TABELA RERSERVAS
CREATE TABLE IF NOT EXISTS RESERVAS(
RESERVA_COD INT PRIMARY KEY,
PASS_CPF VARCHAR(14) NOT NULL,
VOO_ID INT NOT NULL,
CONSTRAINT FK_PASSAGEIROS FOREIGN KEY (PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
CONSTRAINT FK_VOOS FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA RESERVAS
ALTER TABLE RESERVAS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE RESERVAS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE RESERVAS CHANGE DESCRICAO RESERVA_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE RESERVAS DROP RESERVA_DESCRICAO;

#CRIANDO A TABELA VOOS_FUNCIONARIOS
CREATE TABLE IF NOT EXISTS VOOS_FUNCIONARIOS(
VOO_ID INT,
FUNC_ID INT,
PRIMARY KEY(VOO_ID, FUNC_ID),
CONSTRAINT FK_VOOS_OP FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID),
CONSTRAINT FK_FUNCIONARIOS FOREIGN KEY (FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID)
);

#ESTABELECENDO COMANDOS DE ALTER NA TABELA VOOS_FUNCIONARIOS
ALTER TABLE VOOS_FUNCIONARIOS ADD COLUMN DESCRICAO VARCHAR(100) NOT NULL;
ALTER TABLE VOOS_FUNCIONARIOS MODIFY DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE VOOS_FUNCIONARIOS CHANGE DESCRICAO VOFC_DESCRICAO VARCHAR(75) NOT NULL;
ALTER TABLE VOOS_FUNCIONARIOS DROP VOFC_DESCRICAO;

#CRIANDO A TABELA ASTARION
CREATE TABLE IF NOT EXISTS ASTARION(
ASTA_COD INT PRIMARY KEY
);

#ESTABELECENDO COMANDO DE DROP NA TABELA ASTARION
DROP TABLE ASTARION;
